// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID          int32              `json:"id"`
	UserID      int64              `json:"user_id"`
	HashedToken string             `json:"hashed_token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TokenID     string             `json:"token_id"`
}

type User struct {
	ID           int64              `json:"id"`
	Uid          pgtype.UUID        `json:"uid"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         interface{}        `json:"role"`
	TokenVersion int64              `json:"token_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
