// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshTokenByID = `-- name: ConsumeRefreshTokenByID :one
DELETE FROM refresh_tokens WHERE token_id= $1 returning user_id, hashed_token, expires_at, created_at, token_id
`

type ConsumeRefreshTokenByIDRow struct {
	UserID      int64              `json:"user_id"`
	HashedToken string             `json:"hashed_token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TokenID     string             `json:"token_id"`
}

func (q *Queries) ConsumeRefreshTokenByID(ctx context.Context, tokenID string) (ConsumeRefreshTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, consumeRefreshTokenByID, tokenID)
	var i ConsumeRefreshTokenByIDRow
	err := row.Scan(
		&i.UserID,
		&i.HashedToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TokenID,
	)
	return i, err
}

const consumeVerification = `-- name: ConsumeVerification :one
DELETE FROM verification_tokens WHERE id= $1 returning id, user_id, selector, created_at, expires_at
`

type ConsumeVerificationRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int64              `json:"user_id"`
	Selector  string             `json:"selector"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ConsumeVerification(ctx context.Context, id pgtype.UUID) (ConsumeVerificationRow, error) {
	row := q.db.QueryRow(ctx, consumeVerification, id)
	var i ConsumeVerificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Selector,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createBrand = `-- name: CreateBrand :one

INSERT INTO brands (name) values($1) returning id, name
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i Brand
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (name) values($1) returning id, name
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders(shipping_cost_kobo, raw_order_price_in_kobo, discount_type, discount_value, order_total) values($1, $2, $3, $4, $5) returning id, customer_id, created_at, shipping_cost_kobo, raw_order_price_in_kobo, discount_type, discount_value, order_total, status
`

type CreateOrderParams struct {
	ShippingCostKobo    int64       `json:"shipping_cost_kobo"`
	RawOrderPriceInKobo int64       `json:"raw_order_price_in_kobo"`
	DiscountType        interface{} `json:"discount_type"`
	DiscountValue       int64       `json:"discount_value"`
	OrderTotal          int64       `json:"order_total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ShippingCostKobo,
		arg.RawOrderPriceInKobo,
		arg.DiscountType,
		arg.DiscountValue,
		arg.OrderTotal,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.ShippingCostKobo,
		&i.RawOrderPriceInKobo,
		&i.DiscountType,
		&i.DiscountValue,
		&i.OrderTotal,
		&i.Status,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one

INSERT INTO order_items(quantity, price_in_kobo,discount_type, discount_value, item_total) values ($1, $2, $3, $4, $5) returning id, order_id, product_variant_id, quantity, price_in_kobo, discount_type, discount_value, item_total
`

type CreateOrderItemParams struct {
	Quantity      int32       `json:"quantity"`
	PriceInKobo   int64       `json:"price_in_kobo"`
	DiscountType  interface{} `json:"discount_type"`
	DiscountValue int64       `json:"discount_value"`
	ItemTotal     int64       `json:"item_total"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.Quantity,
		arg.PriceInKobo,
		arg.DiscountType,
		arg.DiscountValue,
		arg.ItemTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.PriceInKobo,
		&i.DiscountType,
		&i.DiscountValue,
		&i.ItemTotal,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products(name, description) values ($1, $2) returning id, name, description, brand_id, category_id
`

type CreateProductParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BrandID,
		&i.CategoryID,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one

INSERT INTO product_variants(weight, unit, price_in_kobo, stock) values ($1, $2, $3, $4) returning id, product_id, weight, unit, price_in_kobo, stock
`

type CreateProductVariantParams struct {
	Weight      int32  `json:"weight"`
	Unit        string `json:"unit"`
	PriceInKobo int64  `json:"price_in_kobo"`
	Stock       int32  `json:"stock"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.Weight,
		arg.Unit,
		arg.PriceInKobo,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Weight,
		&i.Unit,
		&i.PriceInKobo,
		&i.Stock,
	)
	return i, err
}

const createShippingRules = `-- name: CreateShippingRules :one

INSERT INTO shipping_rules(max_price_in_kobo, min_price_in_kobo,type, value) values ($1, $2, $3, $4) returning id, min_price_in_kobo, max_price_in_kobo, type, value
`

type CreateShippingRulesParams struct {
	MaxPriceInKobo int64       `json:"max_price_in_kobo"`
	MinPriceInKobo int64       `json:"min_price_in_kobo"`
	Type           interface{} `json:"type"`
	Value          int64       `json:"value"`
}

func (q *Queries) CreateShippingRules(ctx context.Context, arg CreateShippingRulesParams) (ShippingRule, error) {
	row := q.db.QueryRow(ctx, createShippingRules,
		arg.MaxPriceInKobo,
		arg.MinPriceInKobo,
		arg.Type,
		arg.Value,
	)
	var i ShippingRule
	err := row.Scan(
		&i.ID,
		&i.MinPriceInKobo,
		&i.MaxPriceInKobo,
		&i.Type,
		&i.Value,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (name,email,password_hash,token_version,verified_expiry ) values ($1, $2, $3, $4, $5) returning id, uid, name, email, password_hash, role, token_version, created_at, is_verified, verified_expiry
`

type CreateUserParams struct {
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	TokenVersion   int64              `json:"token_version"`
	VerifiedExpiry pgtype.Timestamptz `json:"verified_expiry"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.TokenVersion,
		arg.VerifiedExpiry,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.IsVerified,
		&i.VerifiedExpiry,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, hashed_token, expires_at, created_at, token_id FROM refresh_tokens WHERE token_id= $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, tokenID string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HashedToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TokenID,
	)
	return i, err
}

const getResetPasswordBySelector = `-- name: GetResetPasswordBySelector :one
SELECT verifier_hash, user_id, is_used,expiry FROM password_reset WHERE selector=$1
`

type GetResetPasswordBySelectorRow struct {
	VerifierHash string             `json:"verifier_hash"`
	UserID       int64              `json:"user_id"`
	IsUsed       bool               `json:"is_used"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
}

func (q *Queries) GetResetPasswordBySelector(ctx context.Context, selector string) (GetResetPasswordBySelectorRow, error) {
	row := q.db.QueryRow(ctx, getResetPasswordBySelector, selector)
	var i GetResetPasswordBySelectorRow
	err := row.Scan(
		&i.VerifierHash,
		&i.UserID,
		&i.IsUsed,
		&i.Expiry,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, token_version, is_verified FROM users WHERE email= $1
`

type GetUserByEmailRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	TokenVersion int64       `json:"token_version"`
	IsVerified   pgtype.Bool `json:"is_verified"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.TokenVersion,
		&i.IsVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, token_version, is_verified FROM users WHERE id= $1
`

type GetUserByIDRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	TokenVersion int64       `json:"token_version"`
	IsVerified   pgtype.Bool `json:"is_verified"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.TokenVersion,
		&i.IsVerified,
	)
	return i, err
}

const getVerificationByToken = `-- name: GetVerificationByToken :one
SELECT id, user_id, selector, expires_at, verifier_hash FROM verification_tokens WHERE selector= $1
`

type GetVerificationByTokenRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       int64              `json:"user_id"`
	Selector     string             `json:"selector"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	VerifierHash string             `json:"verifier_hash"`
}

func (q *Queries) GetVerificationByToken(ctx context.Context, selector string) (GetVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getVerificationByToken, selector)
	var i GetVerificationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Selector,
		&i.ExpiresAt,
		&i.VerifierHash,
	)
	return i, err
}

const saveOneTimeToken = `-- name: SaveOneTimeToken :one
INSERT INTO verification_tokens(user_id, selector, expires_at, verifier_hash) values ($1, $2, $3, $4) returning id, user_id, selector, expires_at, verifier_hash
`

type SaveOneTimeTokenParams struct {
	UserID       int64              `json:"user_id"`
	Selector     string             `json:"selector"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	VerifierHash string             `json:"verifier_hash"`
}

type SaveOneTimeTokenRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       int64              `json:"user_id"`
	Selector     string             `json:"selector"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	VerifierHash string             `json:"verifier_hash"`
}

func (q *Queries) SaveOneTimeToken(ctx context.Context, arg SaveOneTimeTokenParams) (SaveOneTimeTokenRow, error) {
	row := q.db.QueryRow(ctx, saveOneTimeToken,
		arg.UserID,
		arg.Selector,
		arg.ExpiresAt,
		arg.VerifierHash,
	)
	var i SaveOneTimeTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Selector,
		&i.ExpiresAt,
		&i.VerifierHash,
	)
	return i, err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refresh_tokens(user_id, hashed_token, expires_at, created_at, token_id) values ($1, $2, $3, $4, $5) returning id, user_id, hashed_token, expires_at, created_at, token_id
`

type SaveRefreshTokenParams struct {
	UserID      int64              `json:"user_id"`
	HashedToken string             `json:"hashed_token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TokenID     string             `json:"token_id"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.UserID,
		arg.HashedToken,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.TokenID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HashedToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TokenID,
	)
	return i, err
}

const saveResetPassword = `-- name: SaveResetPassword :one
INSERT INTO password_reset(verifier_hash, user_id, expiry, selector) values ($1, $2, $3, $4) returning user_id, verifier_hash, expiry, selector
`

type SaveResetPasswordParams struct {
	VerifierHash string             `json:"verifier_hash"`
	UserID       int64              `json:"user_id"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	Selector     string             `json:"selector"`
}

type SaveResetPasswordRow struct {
	UserID       int64              `json:"user_id"`
	VerifierHash string             `json:"verifier_hash"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	Selector     string             `json:"selector"`
}

func (q *Queries) SaveResetPassword(ctx context.Context, arg SaveResetPasswordParams) (SaveResetPasswordRow, error) {
	row := q.db.QueryRow(ctx, saveResetPassword,
		arg.VerifierHash,
		arg.UserID,
		arg.Expiry,
		arg.Selector,
	)
	var i SaveResetPasswordRow
	err := row.Scan(
		&i.UserID,
		&i.VerifierHash,
		&i.Expiry,
		&i.Selector,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users SET password_hash= $1 WHERE id= $2 returning name
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (string, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.PasswordHash, arg.ID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateResetPasswordStatus = `-- name: UpdateResetPasswordStatus :exec
UPDATE users SET is_used= true WHERE id= $1
`

func (q *Queries) UpdateResetPasswordStatus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateResetPasswordStatus, id)
	return err
}

const updateVerificationUsers = `-- name: UpdateVerificationUsers :exec
UPDATE users SET verified_expiry= $1 WHERE id= $2
`

type UpdateVerificationUsersParams struct {
	VerifiedExpiry pgtype.Timestamptz `json:"verified_expiry"`
	ID             int64              `json:"id"`
}

func (q *Queries) UpdateVerificationUsers(ctx context.Context, arg UpdateVerificationUsersParams) error {
	_, err := q.db.Exec(ctx, updateVerificationUsers, arg.VerifiedExpiry, arg.ID)
	return err
}

const updateVerifiedState = `-- name: UpdateVerifiedState :exec
UPDATE users SET is_verified= true WHERE id= $1
`

func (q *Queries) UpdateVerifiedState(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateVerifiedState, id)
	return err
}
