// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumePasswordReset(ctx context.Context, selector string) (ConsumePasswordResetRow, error)
	ConsumeRefreshTokenByID(ctx context.Context, tokenID string) (ConsumeRefreshTokenByIDRow, error)
	ConsumeVerification(ctx context.Context, id pgtype.UUID) (ConsumeVerificationRow, error)
	CreateBrand(ctx context.Context, name string) (Brand, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateShippingRules(ctx context.Context, arg CreateShippingRulesParams) (ShippingRule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRefreshTokenByUserID(ctx context.Context, userID int64) error
	GetRefreshTokenByID(ctx context.Context, tokenID string) (RefreshToken, error)
	GetResetPasswordBySelector(ctx context.Context, selector string) (GetResetPasswordBySelectorRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetVerificationByToken(ctx context.Context, selector string) (GetVerificationByTokenRow, error)
	SaveOneTimeToken(ctx context.Context, arg SaveOneTimeTokenParams) (SaveOneTimeTokenRow, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
	SaveResetPassword(ctx context.Context, arg SaveResetPasswordParams) (SaveResetPasswordRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (string, error)
	UpdateResetPasswordStatus(ctx context.Context, selector string) error
	UpdateVerificationUsers(ctx context.Context, arg UpdateVerificationUsersParams) error
	UpdateVerifiedState(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
